// This file was generated by counterfeiter
package fakes

import (
	"net"
	"sync"

	"code.cloudfoundry.org/diego-ssh/handlers"
)

type FakeDialer struct {
	DialStub        func(net, addr string) (net.Conn, error)
	dialMutex       sync.RWMutex
	dialArgsForCall []struct {
		net  string
		addr string
	}
	dialReturns struct {
		result1 net.Conn
		result2 error
	}
}

func (fake *FakeDialer) Dial(net string, addr string) (net.Conn, error) {
	fake.dialMutex.Lock()
	fake.dialArgsForCall = append(fake.dialArgsForCall, struct {
		net  string
		addr string
	}{net, addr})
	fake.dialMutex.Unlock()
	if fake.DialStub != nil {
		return fake.DialStub(net, addr)
	} else {
		return fake.dialReturns.result1, fake.dialReturns.result2
	}
}

func (fake *FakeDialer) DialCallCount() int {
	fake.dialMutex.RLock()
	defer fake.dialMutex.RUnlock()
	return len(fake.dialArgsForCall)
}

func (fake *FakeDialer) DialArgsForCall(i int) (string, string) {
	fake.dialMutex.RLock()
	defer fake.dialMutex.RUnlock()
	return fake.dialArgsForCall[i].net, fake.dialArgsForCall[i].addr
}

func (fake *FakeDialer) DialReturns(result1 net.Conn, result2 error) {
	fake.DialStub = nil
	fake.dialReturns = struct {
		result1 net.Conn
		result2 error
	}{result1, result2}
}

var _ handlers.Dialer = new(FakeDialer)
