// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"github.com/cloudfoundry-incubator/diego-ssh/handlers"
)

type FakeShellLocator struct {
	ShellPathStub        func() string
	shellPathMutex       sync.RWMutex
	shellPathArgsForCall []struct{}
	shellPathReturns struct {
		result1 string
	}
}

func (fake *FakeShellLocator) ShellPath() string {
	fake.shellPathMutex.Lock()
	fake.shellPathArgsForCall = append(fake.shellPathArgsForCall, struct{}{})
	fake.shellPathMutex.Unlock()
	if fake.ShellPathStub != nil {
		return fake.ShellPathStub()
	} else {
		return fake.shellPathReturns.result1
	}
}

func (fake *FakeShellLocator) ShellPathCallCount() int {
	fake.shellPathMutex.RLock()
	defer fake.shellPathMutex.RUnlock()
	return len(fake.shellPathArgsForCall)
}

func (fake *FakeShellLocator) ShellPathReturns(result1 string) {
	fake.ShellPathStub = nil
	fake.shellPathReturns = struct {
		result1 string
	}{result1}
}

var _ handlers.ShellLocator = new(FakeShellLocator)
