// This file was generated by counterfeiter
package app_fakes

import (
	"sync"

	"github.com/cloudfoundry-incubator/diego-ssh/cf-plugin/models/app"
)

type FakeAppFactory struct {
	GetStub        func(string) (app.App, error)
	getMutex       sync.RWMutex
	getArgsForCall []struct {
		arg1 string
	}
	getReturns struct {
		result1 app.App
		result2 error
	}
}

func (fake *FakeAppFactory) Get(arg1 string) (app.App, error) {
	fake.getMutex.Lock()
	fake.getArgsForCall = append(fake.getArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.getMutex.Unlock()
	if fake.GetStub != nil {
		return fake.GetStub(arg1)
	} else {
		return fake.getReturns.result1, fake.getReturns.result2
	}
}

func (fake *FakeAppFactory) GetCallCount() int {
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	return len(fake.getArgsForCall)
}

func (fake *FakeAppFactory) GetArgsForCall(i int) string {
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	return fake.getArgsForCall[i].arg1
}

func (fake *FakeAppFactory) GetReturns(result1 app.App, result2 error) {
	fake.GetStub = nil
	fake.getReturns = struct {
		result1 app.App
		result2 error
	}{result1, result2}
}

var _ app.AppFactory = new(FakeAppFactory)
